### ISSUE TITLE
file shape_predictor_68_face_landmarks.dat not found

### ISSUE THREAD

**Issue by luthfy13** [narender-rk10/MyProctor.ai-AI-BASED-SMART-ONLINE-EXAMINATION-PROCTORING-SYSYTEM#16]
hello, good morning op.
could u upload the file **shape_predictor_68_face_landmarks.dat**? it's not included in this repo.

i have this error:
```
Traceback (most recent call last):
  File "app.py", line 29, in <module>
    import camera
  File "/home/User/Documents/MyProctor.ai/camera.py", line 26, in <module>
    gaze = GazeTracking()
  File "/home/User/Documents/MyProctor.ai/gaze_tracking/gaze_tracking.py", line 28, in __init__
    self._predictor = dlib.shape_predictor(model_path)
RuntimeError: Unable to open /home/User/Documents/MyProctor.ai/gaze_tracking/trained_models/shape_predictor_68_face_landmarks.dat
```

**Comment by narender-rk10** [comment]
Download shape_predictor_68_face_landmarks.dat model and import it:
https://github.com/italojs/facial-landmarks-recognition/blob/master/shape_predictor_68_face_landmarks.dat?raw=true
