### ISSUE TITLE
[URGENT] Missing Project Files!

### ISSUE THREAD

**Issue by drac-0011** [narender-rk10/MyProctor.ai-AI-BASED-SMART-ONLINE-EXAMINATION-PROCTORING-SYSYTEM#31]
`tensorflow.python.framework.errors_impl.InvalidArgumentError:  Unsuccessful TensorSliceReader constructor: Failed to get matching files on models/pose_model\variables\variables: Not found: FindFirstFile failed for: models/pose_model/variables : The system cannot find the path specified.`

I think you haven't provided all the necessary files required in the /models directory. I had to download a few separetely. But i'm not able to figure out the file mentioned in the above error

**Comment by OlayinkaSoftware** [comment]
Hi Narender,

I am new to Python and I just downloaded this project for learning. After successfully creating a virtualenv and all necessary thing, I am stuck with this error. I have checked everywhere without solution:
****Traceback (most recent call last):
  File "C:\Users\OLAYINKA.ADU\Desktop\Monitor\app.py", line 29, in <module>**
    **import camera
  File "C:\Users\OLAYINKA.ADU\Desktop\Monitor\camera.py", line 292, in <module>
    face_model = get_face_detector()
  File "C:\Users\OLAYINKA.ADU\Desktop\Monitor\face_detector.py", line 20, in get_face_detector
    model = cv2.dnn.readNetFromCaffe(configFile, modelFile)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1138: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "models\res10_300x300_ssd_iter_140000.caffemodel" in function 'cv::dnn::ReadProtoFromBinaryFile'**

Sir, can you kindly assist me please

**Comment by Sonu-rgukt** [comment]
res10_300x300_ssd_iter_140000.caffemodel This file is available on the internet 
just search this file name then you may get a git hub repository

**Comment by Sonu-rgukt** [comment]
> `tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on models/pose_model\variables\variables: Not found: FindFirstFile failed for: models/pose_model/variables : The system cannot find the path specified.`
> 
> I think you haven't provided all the necessary files required in the /models directory. I had to download a few separately. But I'm not able to figure out the file mentioned in the above error

yes, I am also facing the same issue, did you resolve the issue?

**Comment by nugrohowidijatmiko** [comment]
> `tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on models/pose_model\variables\variables: Not found: FindFirstFile failed for: models/pose_model/variables : The system cannot find the path specified.`
> 
> I think you haven't provided all the necessary files required in the /models directory. I had to download a few separetely. But i'm not able to figure out the file mentioned in the above error

  File "C:\Users\asus\Documents\MyProctor4\.venv\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Unsuccessful TensorSliceReader constructor: Failed to get matching files on models/pose_model\variables\variables: Not found: FindFirstFile failed for: models/pose_model/variables : The system cannot find the path specified.
; No such process
         [[node save/RestoreV2 (defined at c:\Users\asus\Documents\MyProctor4\face_landmarks.py:7) ]] [Op:__inference_pruned_14233]

Function call stack:
pruned


I also facing the same issue, did you resolve the issue?
